### ISSUE TITLE
Crashing on short HTTP title elements

### ISSUE THREAD

**Issue by bbriggs** [bbriggs/bitbot#23]
The solution to #20 actually caused a new issue: the bot crashes on titles that are shorter than the allocated buffer for reading titles in.

```
panic: runtime error: slice bounds out of range

goroutine 58 [running]:
github.com/bbriggs/bitbot/bitbot.traverse(0xc420132930, 0x0, 0x0, 0x912b00)
        /home/lkw/go/src/github.com/bbriggs/bitbot/bitbot/links.go:51 +0x111
github.com/bbriggs/bitbot/bitbot.traverse(0xc420132700, 0x0, 0x0, 0x0)
        /home/lkw/go/src/github.com/bbriggs/bitbot/bitbot/links.go:55 +0xb5
github.com/bbriggs/bitbot/bitbot.traverse(0xc420132690, 0x0, 0x0, 0xc42021a200)
        /home/lkw/go/src/github.com/bbriggs/bitbot/bitbot/links.go:55 +0xb5
github.com/bbriggs/bitbot/bitbot.traverse(0xc420132540, 0xc4200f7160, 0xc420132540, 0x0)
        /home/lkw/go/src/github.com/bbriggs/bitbot/bitbot/links.go:55 +0xb5
github.com/bbriggs/bitbot/bitbot.GetHtmlTitle(0x7f528f67aa00, 0xc4200f7140, 0xc4200f7140, 0x7f528f67aa00, 0xc4200f7140)
        /home/lkw/go/src/github.com/bbriggs/bitbot/bitbot/links.go:70 +0x8a
github.com/bbriggs/bitbot/bitbot.lookupPageTitle(0xc42001c5e6, 0x11, 0x0, 0x0)
        /home/lkw/go/src/github.com/bbriggs/bitbot/bitbot/links.go:37 +0x128
github.com/bbriggs/bitbot/bitbot.glob..func4(0xc4204d8280, 0xc4201e06e0, 0x1)
        /home/lkw/go/src/github.com/bbriggs/bitbot/bitbot/links.go:17 +0x38
github.com/bbriggs/bitbot/vendor/github.com/whyrusleeping/hellabot.(*Bot).handleIncomingMessages.func1(0xc4204d8280, 0xc4201e06e0)
        /home/lkw/go/src/github.com/bbriggs/bitbot/vendor/github.com/whyrusleeping/hellabot/hellabot.go:120 +0xa7
created by github.com/bbriggs/bitbot/vendor/github.com/whyrusleeping/hellabot.(*Bot).handleIncomingMessages
        /home/lkw/go/src/github.com/bbriggs/bitbot/vendor/github.com/whyrusleeping/hellabot/hellabot.go:118 +0x11a
```

**Comment by bbriggs** [comment]
Feel free! I'll reserve it for you.

**Comment by sylmoss** [comment]
Thank you. Sorry for the delay, I'm working with it right now.

**Comment by sylmoss** [comment]
Done :)
